# hello-api Kubernetes Deployment with Ingress
# 접근 URL: http://localhost:30080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  namespace: default
  labels:
    app: $APP_NAME
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
        component: backend
    spec:
      containers:
        - name: $APP_NAME
          image: $IMAGE_NAME:$IMAGE_TAG
          imagePullPolicy: Never # 로컬 이미지 사용
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # Health Check 경로 (프로브용)
          readinessProbe:
            httpGet:
              path: /hello?name=HealthCheck
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /hello?name=HealthCheck
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          # 시작 프로브 추가 (Spring Boot 시작 시간 고려)
          startupProbe:
            httpGet:
              path: /hello?name=StartupCheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30 # 150초(5*30) 동안 시작 대기
---
# ClusterIP Service (Ingress에서 사용)
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-service
  namespace: default
  labels:
    app: $APP_NAME
    component: backend
spec:
  selector:
    app: $APP_NAME
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
