apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ui
  template:
    metadata:
      labels:
        app: hello-ui
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hello-ui
          image: n1xda48t.kr.private-ncr.ntruss.com/hello-ui
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-ui-service
spec:
  selector:
    app: hello-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
