-- PostgreSQL 14 DDL (검증 및 수정 완료)

-- 수강신청
DROP TABLE IF EXISTS user_course_appl CASCADE;

-- 교육과정
DROP TABLE IF EXISTS courses CASCADE;

-- 강의실
DROP TABLE IF EXISTS classrooms CASCADE;

-- 강의실사진
DROP TABLE IF EXISTS classroom_photos CASCADE;

-- 지점
DROP TABLE IF EXISTS locations CASCADE;

-- 과목
DROP TABLE IF EXISTS subjects CASCADE;

-- 교육과정과목
DROP TABLE IF EXISTS course_subjects CASCADE;

-- 사용자
DROP TABLE IF EXISTS users CASCADE;


-- 사용자 (다른 테이블의 FK 참조 대상이므로 먼저 생성)
CREATE TABLE users
(
	user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 사용자번호 (자동증가)
	name     VARCHAR(50)  NOT NULL,    -- 이름
	email    VARCHAR(100)  NOT NULL UNIQUE, -- 이메일
	pwd      VARCHAR(100) NOT NULL,    -- 암호
	grade    VARCHAR(100) NOT NULL,    -- 최종학력
	tel      VARCHAR(30)  NULL,        -- 전화
	photo    VARCHAR(255) NULL,        -- 사진
	post_no  CHAR(5)      NULL,        -- 우편번호
	base_address VARCHAR(255) NULL,    -- 기본주소
	detail_address VARCHAR(255) NULL   -- 상세주소
);

CREATE INDEX IX_users ON users (name);

-- 지점
CREATE TABLE locations
(
	location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- 지점번호 (자동증가)
	name        VARCHAR(50) NOT NULL UNIQUE  -- 지점명
);

-- 과목
CREATE TABLE subjects
(
	subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- 과목번호 (자동증가)
	title      VARCHAR(255) NOT NULL UNIQUE  -- 과목명
);

-- 강의실
CREATE TABLE classrooms
(
	classroom_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 강의실번호 (자동증가)
	name         VARCHAR(50) NOT NULL,    -- 교실명
	capacity     INTEGER     NOT NULL,    -- 최대수용인원
	location_id  INTEGER     NOT NULL,    -- 지점번호
	CONSTRAINT FK_locations_TO_classrooms FOREIGN KEY (location_id) REFERENCES locations (location_id),
	CONSTRAINT UK_classrooms UNIQUE (location_id, name)
);

ALTER TABLE classrooms
  ADD CONSTRAINT chk_classrooms_capacity CHECK (capacity > 0);

-- 강의실사진
CREATE TABLE classroom_photos
(
	classroom_photo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 강의실사진번호 (자동증가)
	classroom_id       INTEGER      NOT NULL,    -- 강의실번호
	file_path          VARCHAR(255) NOT NULL,    -- 교실사진
	CONSTRAINT FK_classroom_TO_classroom_photos FOREIGN KEY (classroom_id) REFERENCES classrooms (classroom_id)
);

-- 교육과정
CREATE TABLE courses
(
	course_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 교육과정번호 (자동증가)
	start_date   DATE         NOT NULL,    -- 시작일
	end_date     DATE         NOT NULL,    -- 종료일
	total_hours  INTEGER      NOT NULL,    -- 총강의시간
	day_hours    INTEGER      NOT NULL,    -- 일강의시간
	price        INTEGER      NOT NULL,    -- 수강료
	quantity     INTEGER      NOT NULL,    -- 모집인원
	title        VARCHAR(255) NOT NULL,    -- 교육과정명
	content      TEXT         NOT NULL,    -- 설명
	classroom_id INTEGER      NULL,        -- 강의실번호
	CONSTRAINT FK_classroom_TO_courses FOREIGN KEY (classroom_id) REFERENCES classrooms (classroom_id)
);

CREATE INDEX IX_courses ON courses (title);

ALTER TABLE courses
  ADD CONSTRAINT chk_courses_dates CHECK (end_date >= start_date),
  ADD CONSTRAINT chk_courses_hours CHECK (total_hours > 0 AND day_hours > 0),
  ADD CONSTRAINT chk_courses_price CHECK (price >= 0),
  ADD CONSTRAINT chk_courses_quantity CHECK (quantity >= 0);

-- 수강신청
CREATE TABLE user_course_appl
(
	user_course_appl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 수강신청번호 (자동증가)
	user_id             INTEGER     NOT NULL,    -- 사용자번호
	course_id           INTEGER     NOT NULL,    -- 교육과정번호
	registration_date   DATE        NOT NULL,    -- 신청일
	application_status  VARCHAR(20) NOT NULL,    -- 신청상태
	CONSTRAINT UK_user_course UNIQUE (user_id, course_id),
	CONSTRAINT FK_user_TO_user_course_appl FOREIGN KEY (user_id) REFERENCES users (user_id),
	CONSTRAINT FK_course_TO_user_course_appl FOREIGN KEY (course_id) REFERENCES courses (course_id)
);

ALTER TABLE user_course_appl
  ADD CONSTRAINT chk_user_course_appl_status
  CHECK (application_status IN ('REQUESTED','APPROVED','REJECTED','CANCELLED','COMPLETED'));


-- 교육과정-과목
CREATE TABLE course_subjects
(
	course_id  INTEGER NOT NULL, -- 교육과정번호
	subject_id INTEGER NOT NULL, -- 과목번호
	CONSTRAINT PK_course_subjects PRIMARY KEY (course_id, subject_id),
	CONSTRAINT FK_course_TO_course_subjects FOREIGN KEY (course_id) REFERENCES courses (course_id),
	CONSTRAINT FK_subject_TO_course_subjects FOREIGN KEY (subject_id) REFERENCES subjects (subject_id)
);

-- 코멘트 추가
COMMENT ON TABLE users IS '사용자 정보';
COMMENT ON TABLE courses IS '교육과정';
COMMENT ON TABLE user_course_appl IS '수강신청';
COMMENT ON TABLE classrooms IS '강의실';
COMMENT ON TABLE locations IS '지점';
COMMENT ON TABLE subjects IS '과목';
COMMENT ON TABLE course_subjects IS '교육과정-과목';

CREATE INDEX IF NOT EXISTS ix_classroom_photos_classroom_id ON classroom_photos (classroom_id);
CREATE INDEX IF NOT EXISTS ix_user_course_appl_user_id ON user_course_appl (user_id);
CREATE INDEX IF NOT EXISTS ix_user_course_appl_course_id ON user_course_appl (course_id);
CREATE INDEX IF NOT EXISTS ix_course_subjects_subject_id ON course_subjects (subject_id);

-- 강의실 삭제 시 강의실 사진도 함께 삭제
ALTER TABLE classroom_photos
  DROP CONSTRAINT IF EXISTS FK_classroom_TO_classroom_photos,
  ADD  CONSTRAINT FK_classroom_TO_classroom_photos
       FOREIGN KEY (classroom_id) REFERENCES classrooms(classroom_id)
       ON DELETE CASCADE;



