gitlabUrl: http://host.docker.internal:8929

runnerRegistrationToken: "YG_N9n-9TxCyBJm7tu5B"

rbac:
  create: true

runners:
  config: |
    [[runners]]
      name = "docker-desktop-runner"
      url = "http://host.docker.internal:8929"
      token = "YG_N9n-9TxCyBJm7tu5B"
      executor = "kubernetes"
      clone_url = "http://host.docker.internal:8929"
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "alpine:latest"
        helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:arm64-latest"
        helper_image_flavor = "alpine"
        poll_timeout = 180
        cpu_request = "500m"
        memory_request = "1Gi"
        cpu_limit = "2"
        memory_limit = "4Gi"
        # Docker 소켓 마운트 (중요!)
        [[runners.kubernetes.volumes.host_path]]
          name = "docker-sock"
          mount_path = "/var/run/docker.sock"
          host_path = "/var/run/docker.sock"
        [[runners.kubernetes.env]]
          name = "GIT_SSL_NO_VERIFY"
          value = "true"
        [[runners.kubernetes.env]]
          name = "CI_SERVER_URL"
          value = "http://host.docker.internal:8929"
  privileged: true
